# Generated by Django 3.1.7 on 2021-03-21 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('AC 2 Bed', 'AC 2 Bed'), ('AC 3 Bed', 'AC 3 Bed')], max_length=100)),
                ('check_in_date', models.DateField(null=True)),
                ('check_out_date', models.DateField(null=True)),
                ('visitors_count', models.IntegerField(null=True)),
                ('visitors_name', models.CharField(max_length=5000, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('booking_status', models.CharField(choices=[('0', 'Confirmed'), ('1', 'In-Queue'), ('2', 'Refund'), ('3', 'Cancelled')], max_length=100, null=True)),
                ('paid_amount', models.IntegerField(null=True)),
                ('room_id', models.IntegerField(blank=True, null=True)),
                ('food', models.BooleanField(blank=True, default=0)),
                ('refund_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comfort_of_stay', models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=5, null=True)),
                ('room_cleanliness', models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=5, null=True)),
                ('service_quality', models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=5, null=True)),
                ('additional_feedback', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_AC', models.BooleanField(default=False)),
                ('total_number', models.IntegerField(null=True)),
                ('booked_rooms', models.CharField(max_length=1000, null=True)),
                ('cost', models.IntegerField(null=True)),
                ('capacity', models.IntegerField(null=True)),
                ('room_type', models.CharField(choices=[('AC 2 Bed', 'AC 2 Bed'), ('AC 3 Bed', 'AC 3 Bed')], max_length=100, null=True)),
                ('initial_room_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=100, null=True)),
                ('department', models.CharField(max_length=200, null=True)),
                ('course_type', models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('Phd', 'Phd')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=1000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuestHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('food_availability', models.BooleanField(default=False)),
                ('cost_of_food', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('AC2Bed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='AC2Bed_set', to='OGHBS_APP.room')),
                ('AC3Bed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='AC3Bed_set', to='OGHBS_APP.room')),
                ('customer', models.ManyToManyField(null=True, through='OGHBS_APP.Booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='feedback',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OGHBS_APP.feedback'),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='OGHBS_APP.guesthouse'),
        ),
    ]
