# Generated by Django 3.1.7 on 2021-03-19 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OGHBS_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_AC', models.BooleanField(default=False)),
                ('total_number', models.IntegerField(null=True)),
                ('booked_rooms', models.CharField(max_length=1000, null=True)),
                ('cost', models.IntegerField(null=True)),
                ('capacity', models.IntegerField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='courseType',
            new_name='course_type',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='rollNo',
            new_name='roll_no',
        ),
        migrations.CreateModel(
            name='GuestHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('food_availability', models.BooleanField(default=False)),
                ('cost_of_food', models.IntegerField(null=True)),
                ('AC2Bed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='AC2Bed_set', to='OGHBS_APP.room')),
                ('AC3Bed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='AC3Bed_set', to='OGHBS_APP.room')),
            ],
        ),
    ]
