# Generated by Django 3.1.7 on 2021-03-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OGHBS_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesthouse',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
