# Generated by Django 3.1.7 on 2021-03-22 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OGHBS_APP', '0002_guesthouse_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesthouse',
            name='AC1Bed',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AC1Bed_set', to='OGHBS_APP.room'),
        ),
    ]
