# Generated by Django 3.1.7 on 2021-03-19 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OGHBS_APP', '0002_auto_20210319_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('AC 2 Bed', 'AC 2 Bed'), ('AC 3 Bed', 'AC 3 Bed')], max_length=100)),
                ('check_in_date', models.DateField(null=True)),
                ('check_out_date', models.DateField(null=True)),
                ('visitors_count', models.IntegerField(null=True)),
                ('visitors_name', models.CharField(max_length=5000, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('booking_status', models.BooleanField(default=0)),
                ('paid_amount', models.IntegerField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('guest_house', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='OGHBS_APP.guesthouse')),
            ],
        ),
        migrations.AddField(
            model_name='guesthouse',
            name='customer',
            field=models.ManyToManyField(null=True, through='OGHBS_APP.Booking', to=settings.AUTH_USER_MODEL),
        ),
    ]
