# Generated by Django 3.1.7 on 2021-03-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OGHBS_APP', '0003_auto_20210319_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('AC 2 Bed', 'AC 2 Bed'), ('AC 3 Bed', 'AC 3 Bed')], max_length=100, null=True),
        ),
    ]
