# Generated by Django 3.1.7 on 2021-03-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OGHBS_APP', '0003_guesthouse_ac1bed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_type',
            field=models.CharField(choices=[('AC 2 Bed', 'AC 2 Bed'), ('AC 3 Bed', 'AC 3 Bed'), ('AC 1 Bed', 'AC 1 Bed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('AC 2 Bed', 'AC 2 Bed'), ('AC 3 Bed', 'AC 3 Bed'), ('AC 1 Bed', 'AC 1 Bed')], max_length=100, null=True),
        ),
    ]
