# Generated by Django 3.1.7 on 2021-03-22 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OGHBS_APP', '0004_auto_20210322_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesthouse',
            name='ACDormatory',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ACDormatory_set', to='OGHBS_APP.room'),
        ),
        migrations.AddField(
            model_name='guesthouse',
            name='NAC1Bed',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NAC1Bed_set', to='OGHBS_APP.room'),
        ),
        migrations.AddField(
            model_name='guesthouse',
            name='NAC2Bed',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NAC2Bed_set', to='OGHBS_APP.room'),
        ),
        migrations.AddField(
            model_name='guesthouse',
            name='NAC3Bed',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NAC3Bed_set', to='OGHBS_APP.room'),
        ),
        migrations.AddField(
            model_name='guesthouse',
            name='NACDormatory',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NACDormatory_set', to='OGHBS_APP.room'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_type',
            field=models.CharField(choices=[('AC 2 Bed', 'AC 2 Bed'), ('AC 3 Bed', 'AC 3 Bed'), ('AC 1 Bed', 'AC 1 Bed'), ('ACDormatory', 'ACDormatory'), ('NACDormatory', 'NACDormatory'), ('NAC 2 Bed', 'NAC 2 Bed'), ('NAC 3 Bed', 'NAC 3 Bed'), ('NAC 1 Bed', 'NAC 1 Bed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='guesthouse',
            name='AC2Bed',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AC2Bed_set', to='OGHBS_APP.room'),
        ),
        migrations.AlterField(
            model_name='guesthouse',
            name='AC3Bed',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AC3Bed_set', to='OGHBS_APP.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('AC 2 Bed', 'AC 2 Bed'), ('AC 3 Bed', 'AC 3 Bed'), ('AC 1 Bed', 'AC 1 Bed'), ('ACDormatory', 'ACDormatory'), ('NACDormatory', 'NACDormatory'), ('NAC 2 Bed', 'NAC 2 Bed'), ('NAC 3 Bed', 'NAC 3 Bed'), ('NAC 1 Bed', 'NAC 1 Bed')], max_length=100, null=True),
        ),
    ]
