# Generated by Django 3.1.7 on 2021-03-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OGHBS_APP', '0004_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_id',
            field=models.IntegerField(null=True),
        ),
    ]
