# Generated by Django 3.1.7 on 2021-03-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OGHBS_APP', '0005_booking_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='feedback',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
