# Generated by Django 3.1.7 on 2021-03-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OGHBS_APP', '0006_auto_20210319_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='food',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='guesthouse',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='initial_room_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('0', 'Confirmed'), ('1', 'In-Queue'), ('2', 'Refund'), ('3', 'Cancelled')], max_length=100, null=True),
        ),
    ]
