# Generated by Django 3.1.7 on 2021-03-20 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OGHBS_APP', '0008_auto_20210320_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='feedback',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='OGHBS_APP.feedback'),
        ),
    ]
