# Generated by Django 3.1.7 on 2021-03-20 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OGHBS_APP', '0009_booking_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='feedback',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OGHBS_APP.feedback'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='food',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='refund_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='additional_feedback',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comfort_of_stay',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=5, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='room_cleanliness',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=5, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='service_quality',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=5, null=True),
        ),
        migrations.AlterField(
            model_name='guesthouse',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='guesthouse',
            name='cost_of_food',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
