# Generated by Django 3.1.7 on 2021-03-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OGHBS_APP', '0010_auto_20210320_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
